### ISSUE TITLE
Screenshots not post to JIRA

### ISSUE THREAD

**Issue by Zahorodnii** [reportportal/plugin-bts-jira#14]
![зображення](https://user-images.githubusercontent.com/58936047/73539810-fa827d80-4436-11ea-9db6-d0420991e1fd.png)
![зображення](https://user-images.githubusercontent.com/58936047/73539851-0ff7a780-4437-11ea-88a1-60e4c375054f.png)

**Comment by HardNorth** [comment]
Well at least I'm see now what you are trying to do. OK, we will try to reproduce. But it'll be nice to know your Agents and Plugin versions.

**Comment by Zahorodnii** [comment]
RP - 5.0.0, TestNG agent - 5.0.0-BETA-8, JIRA plugin - 5.1.0-SNAPSHOT from this repo

**Comment by Zahorodnii** [comment]
But for what agent version, JIRA bug posted from RP with POST ISSUE button

**Comment by HardNorth** [comment]
I believe we fixed this

**Comment by Zahorodnii** [comment]
> 
> 
> I believe we fixed this

В какой версии добавили лок? Потому, что я еще не видел фикса
